### ISSUE TITLE
Heartbeats are send continously from endpoint even though endpoint did not start due to an exception

### ISSUE THREAD

**Issue by sanilpaul** [Particular/NServiceBus.Heartbeat#121]
Even though the endpoint failed to start due to an exception in a feature startup task, heartbeats are send continuously indicating endpoints are healthy incorrectly. 
We discovered this issue when we encountered an issue with performance counters Particular/NServiceBus.Metrics.PerformanceCounters#176 . It took a while to track it down as service pulse indicated incorrectly that endpoints are healthy. However, its possible  with exception in any feature start up tasks. 

I have modified your multihosting sample to reproduce the issue [here](https://github.com/sanilpaul/NsbHeartbeatIssue). 

Please note that this is in a multi-hosting scenario. 

![image](https://user-images.githubusercontent.com/484817/112329358-84ba2080-8c8d-11eb-9e80-c2bc22ace352.png)

```
NServiceBus - 7.4.4
NServiceBus.Heartbeat - 3.0.1
NServiceBus.Transport.SqlServer - 6.2.0
Runtime : netcoreapp3.1 
```

**Comment by SeanFeldman** [comment]
This is a Core bug. A follow-up Core issue will be linked.

**Comment by timbussmann** [comment]
The following issue has been raised in NServiceBus about the FeatureStartupTask behavior: https://github.com/Particular/NServiceBus/issues/6015

**Comment by SeanFeldman** [comment]
The heartbeats plugin behaves as expected.
Closing this issue as the discussion about multi-hosting using generic host and handling failing to start endpoint is moved to the NServiceBus issue above.
